from AmplitudeCrafter.parameters.complexParameter import complexParameter
from AmplitudeCrafter.parameters.numberParameter import number
from AmplitudeCrafter.parameters.parameterBase import parameter, ParameterScope
from AmplitudeCrafter.parameters.stringParameter import stringParam
from AmplitudeCrafter.parameters.specialParameter import specialParameter
from AmplitudeCrafter.parameters.shpericalComplexParameter import sphericalComplexParameter
from AmplitudeCrafter.parameters.lambdaParameter import lambdaParameter


UNDERSTOOD_PARAMS = [complexParameter,sphericalComplexParameter,number,specialParameter,lambdaParameter]

FALLBACK_PARAMETERS = [stringParam]